### ISSUE TITLE
added_label / removed_label only works for the last label specified

### ISSUE THREAD

**Issue by tcely** [philschatz/project-bot#47]
I'm trying to use rules in https://github.com/alpinelinux/aports/projects/1#card-21871246 but nothing is done when the label is removed.

You can see my attempt to remove `S-WIP` on https://github.com/alpinelinux/aports/pull/9510

I've determined that only the last `removed_label `rule is working. When I swapped the order of `S-stale` and `S-WIP` then the rule that did not work changed.

Similarly, for the rules in https://github.com/alpinelinux/aports/projects/1#card-21870936 only the last entry for `added_label` is working.

I think I figured out the cause.
https://github.com/philschatz/project-bot/blob/05ca4f9748107ce401005fe613b3093a30059932/src/extract-rules.js#L41

The later rules overwriting earlier arguments could be solved by using an array instead of a Map or the hooks could be changed to operate on a list of label arguments. Which solution do you prefer? @philschatz

**Comment by ondrejbouda** [comment]
Multiple label arguments seems like a better solution to me, consistent with `new_issue` and `new_pullrequest`.

**Comment by philschatz** [comment]
@ondrejbouda Currently, the automation card applies when any list item applies (the rules are OR'd) so it seems like _if_ `added_label` supported multiple arguments it would only apply when all of the following were true:

- at least one of the labels listed in `added_label` was added
- all the labels are on the issue/pull request

That way, if the rule is `added_label **stale** **wontfix**` and the issue has no labels, the following would happen as labels are added to the issue:

1. user adds the `stale` label to the issue. Nothing happens
1. user adds the `wontfix` label to the issue. The Issue is moved
1. user adds the `starred` label to the issue. Nothing happens
